'use client';

import { useEffect, useState } from 'react';
import { AnimatePresence, motion, useScroll, useTransform } from 'framer-motion';
import { ArrowDownRight, ArrowUpRight, Menu, X, ArrowRight, MapPin } from 'lucide-react';

const practices=[
 ['01','Corporate','Strategic counsel for companies, boards and founders navigating material decisions.','Board · Governance · Commercial'],
 ['02','Mergers & Acquisitions','Advice across acquisitions, disposals, joint ventures and shareholder negotiations.','Cross-border · Transactions'],
 ['03','Commercial Disputes','Focused representation when commercial relationships become contested or uncertain.','High stakes · Strategy'],
 ['04','International Arbitration','Independent advocacy and dispute strategy across complex international matters.','Treaty · Institutional · Ad hoc'],
 ['05','Private Clients','Discreet advice for individuals and families with complex assets and interests.','Wealth · Succession'],
 ['06','Real Estate','Legal and commercial thinking for significant development, investment and property matters.','Development · Investment'],
 ['07','Regulatory','Practical advice where regulation, investigations and strategic risk intersect.','Risk · Compliance'],
 ['08','Investigations','Calm, structured counsel for sensitive internal and cross-border investigations.','Confidential · Independent'],
];
const people=[
 ['Amelia Hart','Senior Partner','Corporate & M&A','Amelia advises founders, boards and investors on complex transactions where commercial timing matters as much as legal structure.','London · 18 years'],
 ['Jonathan Reed','Partner','International Disputes','Jonathan represents clients in high-value commercial disputes and international arbitration, with a focus on strategy before procedure.','New York · 16 years'],
 ['Sofia Laurent','Partner','Private Clients','Sofia works with families and private clients on succession, property and cross-border interests requiring discretion.','London · 14 years'],
 ['Daniel Chen','Partner','Cross-Border Transactions','Daniel advises international businesses on transactions spanning multiple jurisdictions and regulatory regimes.','Singapore · 15 years'],
];
const insights=[
 ['MARKETS','The new geography of cross-border transactions','18 SEP 2026','7 MIN'],
 ['DISPUTES','When arbitration becomes strategic','03 SEP 2026','6 MIN'],
 ['PRIVATE CLIENTS','Private capital and the changing property landscape','21 AUG 2026','8 MIN'],
 ['CORPORATE','Five questions to ask before signing an acquisition','09 AUG 2026','5 MIN'],
];

function Reveal({children,delay=0,className='' }:{children:React.ReactNode;delay?:number;className?:string}){return <motion.div className={className} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.8,delay,ease:[.22,1,.36,1]}}>{children}</motion.div>}

function LayerStack(){const [p,setP]=useState({x:0,y:0});return <div className="relative h-[360px] w-full max-w-[500px]" onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();setP({x:(e.clientX-r.left-r.width/2)/18,y:(e.clientY-r.top-r.height/2)/18})}} onPointerLeave={()=>setP({x:0,y:0})} aria-label="Dimensional representation of layered legal documents">
 {['top-10 left-8 rotate-[-6deg]','top-20 left-20 rotate-[4deg]','top-28 left-12 rotate-[-2deg]','top-36 left-28 rotate-[7deg]'].map((c,i)=><motion.div key={i} className={`absolute ${c} h-56 w-80 border border-[#a48b62]/30 bg-[#e9e5dc]/[.04] shadow-2xl backdrop-blur-sm`} animate={{x:p.x*(i+1)*.35,y:p.y*(i+1)*.35,rotateZ:[-6,4,-2,7][i]+p.x*.04}} transition={{type:'spring',stiffness:120,damping:18}}><div className="absolute inset-5 border border-[#a48b62]/15"/><div className="absolute bottom-5 left-5 text-[8px] tracking-[.25em] text-[#a48b62]">CASE FILE / 0{i+1}</div></motion.div>)}
 </div>}

export function VerdictPage(){
 const [menu,setMenu]=useState(false); const [scrolled,setScrolled]=useState(false); const {scrollYProgress}=useScroll(); const line=useTransform(scrollYProgress,[0,1],['0%','100%']);
 useEffect(()=>{const f=()=>setScrolled(window.scrollY>24);window.addEventListener('scroll',f);return()=>window.removeEventListener('scroll',f)},[]);
 return <main className="project-verdict">
  <motion.div className="fixed left-0 top-0 z-[60] h-px bg-[#a48b62]" style={{width:line}} aria-hidden="true"/>
  <header className={`fixed inset-x-0 top-0 z-50 border-b transition-all duration-500 ${scrolled?'border-white/10 bg-[#10100f]/90 py-3 backdrop-blur-xl':'border-transparent bg-transparent py-5'}`}>
   <div className="mx-auto flex max-w-[1500px] items-center justify-between px-5 md:px-8 lg:px-12">
    <a href="#top" className="focus-ring serif text-xl tracking-[.14em]">VERDICT</a>
    <nav className="hidden items-center gap-7 lg:flex" aria-label="Primary"><a className="focus-ring eyebrow" href="#expertise">Expertise</a><a className="focus-ring eyebrow" href="#people">People</a><a className="focus-ring eyebrow" href="#matters">Matters</a><a className="focus-ring eyebrow" href="#insights">Insights</a><a className="focus-ring eyebrow" href="#firm">Firm</a></nav>
    <div className="hidden items-center gap-6 lg:flex"><span className="eyebrow text-white/45">LONDON · NEW YORK · SINGAPORE</span><a href="#contact" className="focus-ring border border-[#a48b62]/60 px-4 py-2 text-[10px] uppercase tracking-[.18em] transition hover:bg-[#a48b62] hover:text-[#10100f]">Speak to us</a></div>
    <button className="focus-ring lg:hidden" onClick={()=>setMenu(true)} aria-label="Open menu"><Menu size={23}/></button>
   </div>
  </header>
  <AnimatePresence>{menu&&<motion.div className="fixed inset-0 z-[70] bg-[#10100f] p-6" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="flex justify-between"><span className="serif text-xl tracking-[.14em]">VERDICT</span><button className="focus-ring" onClick={()=>setMenu(false)} aria-label="Close menu"><X/></button></div><nav className="mt-24 flex flex-col" aria-label="Mobile"><a onClick={()=>setMenu(false)} href="#expertise" className="serif border-b border-white/10 py-5 text-5xl">Expertise</a><a onClick={()=>setMenu(false)} href="#people" className="serif border-b border-white/10 py-5 text-5xl">People</a><a onClick={()=>setMenu(false)} href="#matters" className="serif border-b border-white/10 py-5 text-5xl">Matters</a><a onClick={()=>setMenu(false)} href="#insights" className="serif border-b border-white/10 py-5 text-5xl">Insights</a><a onClick={()=>setMenu(false)} href="#firm" className="serif border-b border-white/10 py-5 text-5xl">Firm</a></nav><div className="mt-12 eyebrow text-white/45">LONDON · NEW YORK · SINGAPORE</div></motion.div>}</AnimatePresence>

  <section id="top" className="relative min-h-screen overflow-hidden border-b border-white/10"><div className="absolute inset-0 hero-image opacity-60"/><div className="absolute inset-0 bg-gradient-to-r from-[#10100f] via-[#10100f]/75 to-transparent"/><div className="relative mx-auto grid min-h-screen max-w-[1500px] grid-cols-12 px-5 pt-28 md:px-8 lg:px-12 lg:pt-36">
   <div className="col-span-12 flex flex-col justify-end pb-16 lg:col-span-8 lg:pb-24"><Reveal><div className="eyebrow mb-8 text-[#a48b62]">VERDICT / SPECIALIST LAW</div><h1 className="serif max-w-4xl text-[clamp(4rem,9.2vw,9.6rem)] leading-[.84] tracking-[-.055em]">Clarity when<br/>the stakes<br/><i>are high.</i></h1></Reveal><Reveal delay={.12}><p className="mt-10 max-w-xl text-base leading-7 text-white/65 md:text-lg">Specialist legal counsel for complex decisions, difficult disputes and opportunities that demand precision.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#contact" className="focus-ring inline-flex items-center gap-3 border border-[#a48b62] px-5 py-3 text-[10px] uppercase tracking-[.2em] transition hover:bg-[#a48b62] hover:text-[#10100f]">Speak to a lawyer <ArrowUpRight size={14}/></a><a href="#expertise" className="focus-ring inline-flex items-center gap-3 px-2 py-3 text-[10px] uppercase tracking-[.2em] text-white/60 hover:text-white">Explore our expertise <ArrowDownRight size={14}/></a></div></Reveal></div>
   <div className="col-span-12 hidden items-end justify-between pb-24 lg:col-span-4 lg:flex"><div className="h-72 w-px bg-white/15"/><div className="max-w-[180px] pb-1 text-right"><div className="eyebrow text-[#a48b62]">REFERENCE / 001</div><p className="mt-3 text-xs leading-5 text-white/45">Independent counsel.<br/>International perspective.</p></div></div>
  </div><div className="absolute bottom-8 left-5 right-5 flex justify-between eyebrow text-white/30 md:left-8 md:right-8 lg:left-12 lg:right-12"><span>01 — 06</span><span>SCROLL TO ENTER</span></div></section>

  <section id="firm" className="border-b border-white/10 bg-[#f1eee7] text-[#10100f]"><div className="mx-auto grid max-w-[1500px] grid-cols-12 px-5 py-28 md:px-8 md:py-40 lg:px-12"><div className="col-span-12 lg:col-span-3"><div className="eyebrow text-black/45">01 / THE FIRM</div></div><Reveal className="col-span-12 mt-10 lg:col-span-8 lg:col-start-5 lg:mt-0"><h2 className="serif text-[clamp(3rem,6.4vw,7rem)] leading-[.92] tracking-[-.04em]">Complexity rewards <i>preparation.</i></h2><p className="mt-10 max-w-2xl text-base leading-7 text-black/60">When decisions carry consequences, clarity matters. We combine specialist expertise with commercial judgement to help clients understand what matters, what changes and what comes next.</p></Reveal></div></section>

  <section id="expertise" className="border-b border-white/10"><div className="mx-auto max-w-[1500px] px-5 py-28 md:px-8 lg:px-12"><Reveal><div className="flex items-end justify-between border-b border-white/15 pb-5"><div><div className="eyebrow text-[#a48b62]">02 / EXPERTISE</div><h2 className="serif mt-4 text-5xl md:text-7xl">Where complexity meets <i>specialism.</i></h2></div><span className="hidden eyebrow text-white/30 md:block">08 PRACTICES</span></div></Reveal><div className="mt-4">{practices.map(([n,t,d,m],i)=><motion.a href="#contact" key={t} className="group grid grid-cols-12 border-b border-white/10 py-7 transition md:py-9" initial={{opacity:0}} whileInView={{opacity:1}} viewport={{once:true}} transition={{delay:i*.04}}><span className="col-span-1 text-[10px] text-[#a48b62]">{n}</span><div className="col-span-8 md:col-span-5"><h3 className="serif text-2xl transition group-hover:translate-x-2 md:text-4xl">{t}</h3><p className="mt-2 max-w-lg text-sm leading-6 text-white/45 md:hidden">{d}</p></div><p className="col-span-4 hidden text-sm leading-6 text-white/45 md:col-span-4 md:block">{d}</p><div className="col-span-3 flex items-center justify-end gap-4 text-right"><span className="hidden text-[9px] uppercase tracking-[.16em] text-white/25 lg:block">{m}</span><ArrowRight className="transition duration-500 group-hover:translate-x-2 group-hover:text-[#a48b62]" size={18}/></div></motion.a>)}</div></div></section>

  <section id="matters" className="bg-[#e9e5dc] text-[#10100f]"><div className="mx-auto grid max-w-[1500px] grid-cols-12 px-5 py-28 md:px-8 md:py-40 lg:px-12"><div className="col-span-12 lg:col-span-5"><Reveal><div className="eyebrow text-black/45">03 / ILLUSTRATIVE MATTER</div><div className="mt-16 overflow-hidden"><div className="h-[480px] bg-[url('https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=85')] bg-cover bg-center grayscale"/><div className="mt-4 flex justify-between eyebrow text-black/40"><span>PROJECT MERIDIAN</span><span>2026</span></div></div></Reveal></div><Reveal delay={.1} className="col-span-12 mt-16 lg:col-span-6 lg:col-start-7 lg:mt-24"><h2 className="serif text-[clamp(3.4rem,6.2vw,7rem)] leading-[.88] tracking-[-.05em]">Protecting value through <i>complexity.</i></h2><p className="mt-9 max-w-xl text-base leading-7 text-black/60">A fictional cross-border acquisition involving multiple jurisdictions, regulatory considerations and shareholder negotiations. The team structured the legal strategy around timing, risk allocation and the client&apos;s commercial objective.</p><div className="mt-14 grid grid-cols-2 gap-y-10 border-t border-black/15 pt-7 text-sm"><div><div className="eyebrow text-black/40">TYPE</div><div className="mt-2">Cross-border M&A</div></div><div><div className="eyebrow text-black/40">JURISDICTIONS</div><div className="mt-2">London · Singapore</div></div><div><div className="eyebrow text-black/40">VALUE</div><div className="mt-2 serif text-3xl">£420m</div></div><div><div className="eyebrow text-black/40">STATUS</div><div className="mt-2">Illustrative portfolio content</div></div></div></Reveal></div></section>

  <section id="people" className="border-b border-white/10"><div className="mx-auto max-w-[1500px] px-5 py-28 md:px-8 md:py-40 lg:px-12"><Reveal><div className="eyebrow text-[#a48b62]">04 / PEOPLE</div><div className="mt-5 flex flex-col justify-between gap-6 border-b border-white/15 pb-8 md:flex-row md:items-end"><h2 className="serif max-w-3xl text-5xl leading-[.92] md:text-7xl">Experience without <i>noise.</i></h2><p className="max-w-sm text-sm leading-6 text-white/45">Senior-led advice for decisions where judgement, discretion and pace matter.</p></div></Reveal><div className="grid grid-cols-1 gap-x-5 md:grid-cols-2">{people.map(([n,t,p,b,c],i)=><Reveal key={n} delay={i*.06} className="group border-b border-white/10 py-8 md:py-12"><div className="grid grid-cols-12 gap-5"><div className={`col-span-5 aspect-[.78] bg-cover bg-center grayscale transition duration-700 group-hover:grayscale-0 ${`portrait-${i+1}`}`}/><div className="col-span-7 flex flex-col justify-between"><div><div className="eyebrow text-[#a48b62]">{t}</div><h3 className="serif mt-3 text-3xl md:text-4xl">{n}</h3><div className="mt-2 text-xs uppercase tracking-[.15em] text-white/35">{p}</div></div><div><p className="text-sm leading-6 text-white/50">{b}</p><div className="mt-6 border-t border-white/10 pt-3 text-[9px] uppercase tracking-[.17em] text-white/30">{c}</div></div></div></div></Reveal>)}</div></div></section>

  <section className="border-b border-white/10 bg-[#171716]"><div className="mx-auto grid max-w-[1500px] grid-cols-12 items-center gap-10 px-5 py-28 md:px-8 md:py-36 lg:px-12"><Reveal className="col-span-12 lg:col-span-7"><div className="eyebrow text-[#a48b62]">05 / WHY VERDICT</div><h2 className="serif mt-6 text-[clamp(3.3rem,6.3vw,7rem)] leading-[.9]">Advice beyond<br/><i>the obvious.</i></h2></Reveal><div className="col-span-12 lg:col-span-5">{[['01','Commercial judgement','Legal advice should understand the business behind the decision.'],['02','Specialist thinking','Deep expertise where complexity cannot be solved with general answers.'],['03','International perspective','One matter can cross borders. Our thinking does too.']].map(([n,t,d],i)=><Reveal key={n} delay={i*.08} className="border-t border-white/10 py-7"><div className="grid grid-cols-6 gap-4"><span className="eyebrow text-[#a48b62]">{n}</span><div className="col-span-5"><h3 className="serif text-2xl">{t}</h3><p className="mt-3 text-sm leading-6 text-white/45">{d}</p></div></div></Reveal>)}</div></div></section>

  <section className="border-b border-white/10 bg-[#f1eee7] text-[#10100f]"><div className="mx-auto max-w-[1500px] px-5 py-28 md:px-8 md:py-36 lg:px-12"><Reveal><div className="flex items-end justify-between border-b border-black/15 pb-6"><div><div className="eyebrow text-black/45">06 / SELECTED MATTERS</div><h2 className="serif mt-4 text-5xl md:text-7xl">Illustrative matters.</h2></div><span className="hidden text-[10px] uppercase tracking-[.2em] text-black/35 md:block">Portfolio concept / not actual results</span></div></Reveal><div className="divide-y divide-black/15">{[['£420m','Cross-border acquisition'],['€180m','International arbitration'],['£95m','Private real estate transaction'],['14','Jurisdictions coordinated']].map(([v,d],i)=><Reveal key={v} delay={i*.05} className="grid grid-cols-12 items-baseline py-8 md:py-10"><div className="col-span-6 serif text-5xl md:text-7xl">{v}</div><div className="col-span-5 text-sm text-black/55 md:text-base">{d}</div><div className="col-span-1 text-right text-xs text-black/30">0{i+1}</div></Reveal>)}</div></div></section>

  <section className="border-b border-white/10"><div className="mx-auto max-w-[1500px] px-5 py-28 md:px-8 md:py-36 lg:px-12"><Reveal><div className="eyebrow text-[#a48b62]">07 / HOW WE THINK</div><h2 className="serif mt-5 text-5xl md:text-7xl">A disciplined route<br/><i>through uncertainty.</i></h2></Reveal><div className="relative mt-20"><div className="absolute bottom-0 left-[11px] top-0 w-px bg-white/10"/><motion.div className="absolute left-[10px] top-0 w-[2px] origin-top bg-[#a48b62]" style={{height:'100%'}}/><div className="space-y-0">{[['01','Understand','We identify the commercial objective before defining the legal problem.'],['02','Analyse','We isolate risk, opportunity and competing interests.'],['03','Advise','We translate complexity into clear options.'],['04','Act','We move decisively when a decision has been made.'],['05','Resolve','We stay involved until the matter is complete.']].map(([n,t,d],i)=><Reveal key={n} delay={i*.04} className="relative grid grid-cols-12 border-b border-white/10 py-10 pl-10 md:py-14"><span className="absolute -left-[1px] top-11 h-6 w-6 rounded-full border border-[#a48b62] bg-[#10100f] md:top-[54px]"/><span className="col-span-2 eyebrow text-[#a48b62]">{n}</span><h3 className="serif col-span-4 text-3xl md:text-4xl">{t}</h3><p className="col-span-6 max-w-xl text-sm leading-6 text-white/45 md:text-base">{d}</p></Reveal>)}</div></div></div></section>

  <section id="insights" className="border-b border-white/10 bg-[#f1eee7] text-[#10100f]"><div className="mx-auto max-w-[1500px] px-5 py-28 md:px-8 md:py-36 lg:px-12"><Reveal><div className="eyebrow text-black/45">08 / INSIGHTS</div><div className="mt-5 flex items-end justify-between border-b border-black/15 pb-7"><h2 className="serif text-5xl md:text-7xl">The VERDICT journal.</h2><ArrowUpRight className="hidden md:block"/></div></Reveal><div className="divide-y divide-black/15">{insights.map(([cat,t,date,time],i)=><a href="#contact" key={t} className="group grid grid-cols-12 items-center py-7 transition hover:pl-2 md:py-9"><span className="col-span-2 text-[9px] uppercase tracking-[.18em] text-black/40">{cat}</span><h3 className="serif col-span-8 text-2xl md:text-4xl">{t}</h3><div className="col-span-2 text-right text-[9px] uppercase tracking-[.16em] text-black/35">{date}<br/>{time}</div></a>)}</div></div></section>

  <section className="border-b border-white/10"><div className="mx-auto grid max-w-[1500px] grid-cols-12 px-5 py-28 md:px-8 md:py-36 lg:px-12"><Reveal className="col-span-12 lg:col-span-6"><div className="eyebrow text-[#a48b62]">09 / GLOBAL PRESENCE</div><h2 className="serif mt-5 text-5xl md:text-7xl">Local knowledge.<br/><i>International reach.</i></h2><p className="mt-8 max-w-xl text-sm leading-6 text-white/45">Three offices, one connected approach. We work across borders without losing the context that makes local advice useful.</p></Reveal><div className="relative col-span-12 mt-16 h-[430px] overflow-hidden border border-white/10 map-grid lg:col-span-6 lg:mt-0"><svg viewBox="0 0 800 430" className="absolute inset-0 h-full w-full opacity-60" aria-label="Abstract map connecting London, New York and Singapore"><path d="M125 205 C280 110 380 175 620 300" fill="none" stroke="#a48b62" strokeWidth="1" strokeDasharray="4 7"/><path d="M125 205 C270 240 410 230 620 300" fill="none" stroke="#a48b62" strokeWidth="1" strokeDasharray="2 8"/><circle cx="125" cy="205" r="4" fill="#a48b62"/><circle cx="360" cy="205" r="4" fill="#a48b62"/><circle cx="620" cy="300" r="4" fill="#a48b62"/></svg><div className="absolute left-[12%] top-[43%] eyebrow">LONDON<br/><span className="text-white/35">Primary office</span></div><div className="absolute left-[45%] top-[43%] eyebrow">NEW YORK<br/><span className="text-white/35">Americas</span></div><div className="absolute bottom-[25%] right-[8%] text-right eyebrow">SINGAPORE<br/><span className="text-white/35">Asia-Pacific</span></div></div></div></section>

  <section className="relative overflow-hidden border-b border-white/10"><div className="absolute inset-0 private-image bg-cover bg-center opacity-25"/><div className="absolute inset-0 bg-[#10100f]/70"/><div className="relative mx-auto grid max-w-[1500px] grid-cols-12 px-5 py-32 md:px-8 md:py-44 lg:px-12"><Reveal className="col-span-12 lg:col-span-8"><div className="eyebrow text-[#a48b62]">10 / PRIVATE CLIENTS</div><h2 className="serif mt-6 text-[clamp(3.6rem,7vw,8rem)] leading-[.86]">Some matters<br/>should remain <i>private.</i></h2><p className="mt-10 max-w-xl text-base leading-7 text-white/55">For individuals and families navigating complex assets, succession, property and international interests, discretion is part of the advice.</p><div className="mt-12 grid max-w-xl grid-cols-2 gap-y-4 text-xs uppercase tracking-[.15em] text-white/50">{['Private wealth','Succession','Property','Family governance','Cross-border matters'].map(x=><div key={x}>— {x}</div>)}</div></Reveal></div></section>

  <section className="border-b border-white/10 bg-[#e9e5dc] text-[#10100f]"><div className="mx-auto grid max-w-[1500px] grid-cols-12 px-5 py-28 md:px-8 md:py-36 lg:px-12"><div className="col-span-12 lg:col-span-5"><Reveal><div className="eyebrow text-black/45">11 / INSIDE THE MATTER</div><div className="article-image mt-8 h-[500px] bg-cover bg-center grayscale"/></Reveal></div><Reveal delay={.1} className="col-span-12 mt-14 lg:col-span-6 lg:col-start-7 lg:mt-20"><div className="eyebrow text-black/45">ILLUSTRATIVE CASE STUDY</div><h2 className="serif mt-5 text-5xl leading-[.9] md:text-7xl">Inside the matter.</h2><p className="mt-8 text-base leading-7 text-black/60">A fictional editorial account of an international legal issue where timing, regulation and shareholder alignment pulled in different directions.</p><div className="mt-12 space-y-7">{[['Context','A multinational group considered a strategic acquisition across two regulatory environments.'],['Challenge','The commercial timetable was compressed while shareholder and regulatory interests diverged.'],['Approach','The legal strategy was built around scenario planning, negotiation leverage and clear decision points.'],['Outcome','The illustrative matter concluded with an agreed structure designed to preserve optionality.']].map(([t,d])=><div key={t} className="border-t border-black/15 pt-5"><div className="eyebrow text-black/40">{t}</div><p className="mt-2 max-w-xl text-sm leading-6 text-black/60">{d}</p></div>)}</div></Reveal></div></section>

  <section id="contact" className="relative overflow-hidden"><div className="absolute inset-0 opacity-20 hero-image bg-cover bg-center"/><div className="absolute inset-0 bg-[#10100f]/90"/><div className="relative mx-auto max-w-[1500px] px-5 py-32 md:px-8 md:py-44 lg:px-12"><Reveal><div className="eyebrow text-[#a48b62]">12 / CONTACT</div><h2 className="serif mt-6 max-w-5xl text-[clamp(4rem,9vw,10rem)] leading-[.82] tracking-[-.05em]">Have a difficult<br/>decision <i>ahead?</i></h2><p className="mt-10 max-w-xl text-base leading-7 text-white/50">Start with a conversation. Tell us what you&apos;re facing and we&apos;ll help you understand the next move.</p><div className="mt-9 flex flex-wrap gap-4"><a href="mailto:hello@verdict.example" className="focus-ring inline-flex items-center gap-3 border border-[#a48b62] px-6 py-4 text-[10px] uppercase tracking-[.2em] transition hover:bg-[#a48b62] hover:text-[#10100f]">Speak to us <ArrowUpRight size={15}/></a><a href="#expertise" className="focus-ring inline-flex items-center gap-3 px-2 py-4 text-[10px] uppercase tracking-[.2em] text-white/55 hover:text-white">View expertise <ArrowDownRight size={15}/></a></div></Reveal><div className="mt-28 grid grid-cols-3 border-t border-white/10 pt-6"><div><div className="eyebrow text-white/30">LONDON</div><div className="mt-2 text-xs text-white/55">Primary office</div></div><div><div className="eyebrow text-white/30">NEW YORK</div><div className="mt-2 text-xs text-white/55">Americas</div></div><div><div className="eyebrow text-white/30">SINGAPORE</div><div className="mt-2 text-xs text-white/55">Asia-Pacific</div></div></div></div></section>

  <footer className="border-t border-white/10"><div className="mx-auto max-w-[1500px] px-5 py-14 md:px-8 lg:px-12"><div className="grid grid-cols-2 gap-12 md:grid-cols-4"><div className="col-span-2"><div className="serif text-3xl tracking-[.14em]">VERDICT</div><div className="mt-3 text-xs uppercase tracking-[.18em] text-white/35">Specialist Law</div></div><div><div className="eyebrow text-[#a48b62]">Navigate</div><div className="mt-4 grid gap-2 text-sm text-white/55"><a href="#expertise">Expertise</a><a href="#people">People</a><a href="#matters">Matters</a><a href="#insights">Insights</a><a href="#firm">Firm</a></div></div><div><div className="eyebrow text-[#a48b62]">Contact</div><div className="mt-4 grid gap-2 text-sm text-white/55"><a href="mailto:hello@verdict.example">hello@verdict.example</a><a href="tel:+442000000000">+44 20 0000 0000</a><span>LinkedIn · Instagram</span></div></div></div><div className="mt-14 flex flex-col justify-between gap-4 border-t border-white/10 pt-5 text-[9px] uppercase tracking-[.16em] text-white/25 md:flex-row"><span>© 2026 VERDICT. Concept project.</span><span>Privacy · Terms · Accessibility</span></div></div></footer>
 </main>
}
