"use client";
import { useState } from "react";
import { ArrowUpRight, Menu, X } from "lucide-react";
const homes=[['01','The Arches','A quiet three-bedroom residence with garden views.','₹ 4.8 Cr'],['02','North House','A sculptural family home shaped around light and privacy.','₹ 7.2 Cr'],['03','Monument 27','A limited collection of contemporary city residences.','₹ 9.6 Cr']];
export default function MonumentPage(){const[open,setOpen]=useState(false);return <main className="monument-site bg-[#ece9e2] text-[#171717]">
<header className="fixed inset-x-0 top-0 z-50 border-b border-black/10 bg-[#ece9e2]/80 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8"><a href="#top" className="font-serif text-xl tracking-[.2em]">MONUMENT</a><nav className="hidden gap-8 text-[10px] uppercase tracking-[.2em] text-black/55 md:flex"><a href="#collection">Collection</a><a href="#philosophy">Philosophy</a><a href="#contact">Contact</a></nav><a href="#contact" className="hidden border border-black/20 px-5 py-2.5 text-[10px] uppercase tracking-[.2em] sm:inline-flex">Enquire</a><button onClick={()=>setOpen(true)} className="md:hidden" aria-label="Open menu"><Menu/></button></div></header>
{open&&<div className="fixed inset-0 z-[60] bg-[#ece9e2] p-6"><button className="float-right" onClick={()=>setOpen(false)} aria-label="Close menu"><X/></button><nav className="mt-24 grid gap-7 font-serif text-5xl"><a href="#collection" onClick={()=>setOpen(false)}>Collection</a><a href="#philosophy" onClick={()=>setOpen(false)}>Philosophy</a><a href="#contact" onClick={()=>setOpen(false)}>Contact</a></nav></div>}
<section id="top" className="relative min-h-[92svh] overflow-hidden"><div className="absolute inset-0 monument-hero-image"/><div className="absolute inset-0 bg-gradient-to-t from-black/65 via-black/10 to-black/20"/><div className="relative mx-auto flex min-h-[92svh] max-w-7xl items-end px-5 pb-14 sm:px-8 sm:pb-20"><div className="text-white"><p className="text-[10px] uppercase tracking-[.35em] text-white/65">Independent property group · Mumbai</p><h1 className="mt-6 max-w-5xl font-serif text-7xl leading-[.78] tracking-[-.05em] sm:text-[10rem]">Spaces<br/><em className="text-white/60">with presence.</em></h1><div className="mt-8 flex flex-wrap gap-3"><a href="#collection" className="inline-flex items-center gap-2 bg-white px-6 py-3.5 text-[10px] uppercase tracking-[.2em] text-black">Explore collection <ArrowUpRight size={14}/></a><a href="#contact" className="border border-white/30 px-6 py-3.5 text-[10px] uppercase tracking-[.2em]">Private enquiry</a></div></div></div></section>
<section id="philosophy" className="mx-auto grid max-w-7xl gap-12 px-5 py-24 sm:px-8 sm:py-36 lg:grid-cols-[.65fr_1.35fr]"><p className="text-[10px] uppercase tracking-[.28em] text-black/35">01 / Our philosophy</p><div><h2 className="max-w-4xl font-serif text-5xl leading-[.92] sm:text-7xl">Architecture that gives life <em className="text-black/35">room to breathe.</em></h2><p className="mt-9 max-w-2xl text-base leading-8 text-black/55">MONUMENT develops considered residences in locations with character. We care about proportion, material, natural light and the feeling a place leaves behind.</p></div></section>
<section id="collection" className="border-y border-black/10 bg-[#e4e0d7]"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8 sm:py-32"><div className="flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-[.28em] text-black/35">02 / The collection</p><h2 className="mt-5 font-serif text-6xl sm:text-8xl">Selected homes.</h2></div><span className="text-xs text-black/35">03 residences</span></div><div className="mt-12 grid gap-5 md:grid-cols-3">{homes.map(([n,name,desc,price],i)=><article key={name} className="group"><div className={`monument-card monument-card-${i} aspect-[4/5] overflow-hidden`}/><div className="border-b border-black/15 py-5"><div className="flex justify-between text-[10px] uppercase tracking-[.18em] text-black/35"><span>{n}</span><span>{price}</span></div><h3 className="mt-3 font-serif text-3xl">{name}</h3><p className="mt-2 text-sm leading-6 text-black/50">{desc}</p><button className="mt-5 inline-flex items-center gap-2 text-[10px] uppercase tracking-[.18em]">View residence <ArrowUpRight size={14}/></button></div></article>)}</div></div></section>
<section className="mx-auto grid max-w-7xl gap-10 px-5 py-24 sm:px-8 sm:py-32 lg:grid-cols-2"><div className="monument-detail-image min-h-[500px]"/><div className="flex flex-col justify-center lg:pl-10"><p className="text-[10px] uppercase tracking-[.28em] text-black/35">03 / Beyond the address</p><h2 className="mt-5 font-serif text-6xl leading-[.85] sm:text-8xl">Quietly<br/><em className="text-black/35">distinct.</em></h2><p className="mt-8 max-w-md text-sm leading-7 text-black/55">From the first sketch to the final material, every MONUMENT residence is shaped around a simple idea: the best luxury does not need to announce itself.</p></div></section>
<section id="contact" className="border-t border-black/10 px-5 py-28 text-center sm:px-8 sm:py-40"><p className="text-[10px] uppercase tracking-[.28em] text-black/35">04 / Private enquiries</p><h2 className="mx-auto mt-6 max-w-4xl font-serif text-6xl leading-[.85] sm:text-9xl">Find your<br/><em className="text-black/35">next address.</em></h2><p className="mx-auto mt-8 max-w-md text-sm leading-7 text-black/50">Speak with our private client team about current and upcoming residences.</p><a href="mailto:hello@monument.example" className="mt-9 inline-flex border border-black/25 px-8 py-4 text-[10px] uppercase tracking-[.2em]">Make an enquiry</a></section>
<footer className="border-t border-black/10 px-5 py-9 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 sm:flex-row"><div><div className="font-serif text-xl tracking-[.2em]">MONUMENT</div><p className="mt-1 text-[10px] uppercase tracking-[.18em] text-black/30">Property group · Mumbai</p></div><p className="text-[10px] uppercase tracking-[.18em] text-black/30">© 2026 MONUMENT · Concept Project</p></div></footer></main>}
