'use client';

import { useEffect, useMemo, useState } from 'react';
import { motion, AnimatePresence, useReducedMotion } from 'framer-motion';
import { ArrowRight, Check, ChevronRight, Command, FileText, Menu, Play, Search, Settings2, ShieldCheck, Sparkles, X, Zap } from 'lucide-react';

type Tab = 'Overview'|'Timeline'|'Tasks'|'AI';
type Tour = 'Plan'|'Build'|'Review'|'Launch';

const nav = ['Product','Platform','Solutions','Resources','Pricing'];
const useCases = {
  'Product Teams': {copy:'Turn product signals into decisions, priorities and a launch plan everyone can see.', metric:'31% faster decisions', workflow:['Roadmap sync','Blocker detection','Launch review'], icon:'P'},
  'Operations': {copy:'Connect recurring work, owners and operating context so nothing important disappears between handoffs.', metric:'42% fewer handoff gaps', workflow:['Capture request','Route owner','Close loop'], icon:'O'},
  'Agencies': {copy:'Keep client context, project health and next actions in one shared command center.', metric:'18 hrs saved / month', workflow:['Client brief','Delivery pulse','Approval queue'], icon:'A'},
  'Founders': {copy:'See the whole company without becoming the bottleneck. ORBIT surfaces what needs your attention.', metric:'9.4h recovered / week', workflow:['Company pulse','Decision queue','Founder review'], icon:'F'},
  'Remote Teams': {copy:'Make async work feel connected by turning meetings, docs and activity into organizational memory.', metric:'2.3× faster async', workflow:['Meeting notes','Context graph','Action feed'], icon:'R'}
} as const;

function Button({children,secondary=false,onClick}:{children:React.ReactNode;secondary?:boolean;onClick?:()=>void}){
 return <button onClick={onClick} className={secondary?'btn btn-secondary':'btn'}>{children}<ArrowRight size={15}/></button>
}
function SectionLabel({children,index}:{children:string;index:string}){return <div className="label-row"><span>{index} /</span><b>{children}</b></div>}

function OrbitCore(){
 const reduce=useReducedMotion(); const nodes=[['PROJECTS',0],['PEOPLE',90],['KNOWLEDGE',180],['AI',270]] as const;
 return <div className="orbit-visual" aria-label="ORBIT connected platform visualization">
   <motion.div className="orbit-ring r1" animate={reduce?{}:{rotate:360}} transition={{duration:34,repeat:Infinity,ease:'linear'}} />
   <motion.div className="orbit-ring r2" animate={reduce?{}:{rotate:-360}} transition={{duration:22,repeat:Infinity,ease:'linear'}} />
   <motion.div className="orbit-core"><span>ORBIT</span><small>CONNECTED WORK</small></motion.div>
   {nodes.map(([name,angle],i)=><motion.div key={name} className="orbit-node" style={{'--angle':`${angle}deg`} as React.CSSProperties} whileHover={{scale:1.14}}><span>{i+1}</span>{name}</motion.div>)}
   <div className="orbit-cross x"/><div className="orbit-cross y"/>
 </div>
}

function CommandCenter(){
 const [tab,setTab]=useState('Workspace'); const [done,setDone]=useState([false,false,false]); const [ai,setAi]=useState(false);
 return <div className="command-shell panel glow">
   <div className="app-top"><div className="app-brand"><span className="dot"/>ORBIT <i>workspace</i></div><div className="app-tabs">{['Workspace','Activity','AI'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div><div className="avatar-stack"><span>MR</span><span>SK</span><span>+6</span></div></div>
   <div className="app-body">
    <aside><small>PROJECT</small><strong>Website Relaunch</strong><div className="side-line"><span>Overview</span><b>72%</b></div><div className="progress"><i style={{width:'72%'}}/></div>{['Home','Product','Analytics','Launch'].map(x=><div className="side-item" key={x}>{x}<span>›</span></div>)}<div className="side-bottom"><Settings2 size={14}/> Workspace settings</div></aside>
    <main>
      {tab==='Workspace' && <>
       <div className="app-heading"><div><small>PROJECT / WEBSITE RELAUNCH</small><h3>Move the launch forward.</h3></div><button className="command-btn"><Command size={13}/> K</button></div>
       <div className="app-grid"><div className="mini-card timeline"><div className="mini-title">NEXT MILESTONE <b>Sep 28</b></div><div className="timeline-line"><span/><span/><span/><span/></div><div className="timeline-labels"><span>Discovery</span><span>Build</span><span>QA</span><span>Launch</span></div></div><div className="mini-card health"><div className="mini-title">PROJECT HEALTH</div><strong>Good</strong><span>3 decisions waiting</span></div></div>
       <div className="work-row"><div className="tasks"><div className="mini-title">TODAY&apos;S WORK <b>3 / 6</b></div>{['Finalize homepage','Analytics integration','Mobile QA'].map((x,i)=><button className={'task '+(done[i]?'complete':'')} key={x} onClick={()=>setDone(d=>d.map((v,j)=>j===i?!v:v))}><span>{done[i]?<Check size={12}/>:''}</span>{x}<em>{i===0?'Maya':i===1?'Daniel':'Alex'}</em></button>)}</div><div className="ai-card"><div className="ai-label"><Sparkles size={14}/> ORBIT AI</div><h4>3 decisions are waiting.</h4><p>Homepage copy, analytics ownership and final mobile QA need attention.</p><button onClick={()=>setAi(true)}>Reveal next action <ArrowRight size={13}/></button></div></div>
       </>}
       {tab==='Activity' && <div className="activity"><div className="app-heading"><div><small>LIVE ACTIVITY</small><h3>What changed while you were away.</h3></div></div>{['Maya approved homepage direction','Daniel connected analytics to the launch project','ORBIT detected a QA dependency','Sofia added a launch-risk note'].map((x,i)=><div className="activity-item" key={x}><span>{['MA','DK','AI','SO'][i]}</span><div><strong>{x}</strong><small>{i+1}h ago · Website Relaunch</small></div></div>)}</div>}
       {tab==='AI' && <div className="activity"><div className="app-heading"><div><small>ASK ORBIT</small><h3>What should the team do next?</h3></div></div><div className="ai-answer"><Sparkles size={18}/><p>Start with the homepage approval. It unblocks the final content pass, which then lets mobile QA begin. I would schedule a 20-minute review with Maya and Daniel.</p><button onClick={()=>setAi(true)}>Create review task <ArrowRight size={13}/></button></div></div>}
    </main>
   </div>
   <AnimatePresence>{ai&&<motion.div className="toast" initial={{y:30,opacity:0}} animate={{y:0,opacity:1}} exit={{y:30,opacity:0}}><Check size={15}/> Review task created locally <button onClick={()=>setAi(false)}><X size={14}/></button></motion.div>}</AnimatePresence>
 </div>
}

export function OrbitPage(){
 const [menu,setMenu]=useState(false); const [cmd,setCmd]=useState(false); const [projectTab,setProjectTab]=useState<Tab>('Overview'); const [meeting,setMeeting]=useState<'transcript'|'actions'>('transcript'); const [search,setSearch]=useState(''); const [auto,setAuto]=useState([true,false]); const [caseName,setCaseName]=useState<keyof typeof useCases>('Product Teams'); const [tour,setTour]=useState<Tour>('Plan'); const [annual,setAnnual]=useState(false); useEffect(()=>{const f=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setCmd(v=>!v)}};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[]);
 const result=useMemo(()=>['Pricing Strategy — June 18','Product Meeting — June 20','Decision Log — June 21'].filter(x=>!search||x.toLowerCase().includes(search.toLowerCase())),[search]);
 const tourData={Plan:['Product brief','AI planning','Owners assigned'],Build:['Sprint pulse','Dependencies','Daily focus'],Review:['QA queue','Decision log','Risk review'],Launch:['Launch candidate','Readiness score','Go / no-go']} as const;
 return <div className="site noise project-orbit">
  <header className="nav"><a className="logo" href="#top">ORBIT</a><nav>{nav.map(x=><a key={x} href={'#'+x.toLowerCase()}>{x}</a>)}</nav><div className="nav-right"><span className="status"><i/> SYSTEM ONLINE</span><a href="#pricing">Sign In</a><Button>Get Started</Button><button className="menu-toggle" onClick={()=>setMenu(v=>!v)}>{menu?<X/>:<Menu/>}</button></div></header>
  <AnimatePresence>{menu&&<motion.div className="mobile-menu" initial={{opacity:0,y:-10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-10}}>{nav.map(x=><a key={x} href={'#'+x.toLowerCase()} onClick={()=>setMenu(false)}>{x}<ChevronRight size={16}/></a>)}<a href="#pricing">Sign In</a><Button>Get Started</Button></motion.div>}</AnimatePresence>
  <main id="top">
   <section className="hero orbit-grid"><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> AI-POWERED OPERATING SYSTEM</div><h1>See the work.<br/><em>Move the work.</em></h1><p>ORBIT connects your projects, people and knowledge — then uses AI to help your team decide what happens next.</p><div className="hero-actions"><Button>Start Free</Button><button className="watch"><span><Play size={13}/></span> Watch the Product</button></div><small className="note">No credit card required.</small></div><motion.div className="hero-product" initial={{opacity:0,y:35}} animate={{opacity:1,y:0}} transition={{duration:.8,delay:.15}}><CommandCenter/></motion.div></section>

   <section className="statement section" id="product"><SectionLabel index="01">THE PLATFORM</SectionLabel><div className="statement-grid"><h2>Your team already has the information.<br/><span>ORBIT connects it.</span></h2><div><p>Instead of another tool that creates more work, ORBIT turns the work your team is already doing into context, decisions and momentum.</p><a href="#platform">Explore the system <ArrowRight size={15}/></a></div></div></section>

   <section className="ecosystem section orbit-grid" id="platform"><SectionLabel index="02">THE ECOSYSTEM</SectionLabel><div className="section-intro"><h2>Everything moving.<br/><span>One intelligent orbit.</span></h2><p>Projects, people, knowledge and AI share the same context layer — so every action makes the next action clearer.</p></div><OrbitCore/><div className="ecosystem-list">{[['Projects','Plan and track outcomes.'],['People','Know who owns what.'],['Knowledge','Find the why behind decisions.'],['Meetings','Turn conversation into action.'],['AI','Reason across your workspace.'],['Automation','Let systems handle the repeatable.']].map(([a,b],i)=><div key={a}><span>0{i+1}</span><strong>{a}</strong><p>{b}</p></div>)}</div></section>

   <section className="ai-section section"><SectionLabel index="03">AI COPILOT</SectionLabel><div className="split-title"><h2>AI that knows what your team<br/><span>is trying to do.</span></h2><p>Not a chatbot floating beside your work. ORBIT reasons over the context already inside your workspace.</p></div><div className="copilot panel"><div className="chat-side"><div className="chat-top"><Sparkles size={15}/> ASK ORBIT <span>context: entire workspace</span></div><div className="message user">What&apos;s blocking the website launch?</div><div className="message bot"><b>ORBIT AI</b><p>Three things are currently slowing the launch:</p><ol><li><b>Homepage copy</b> awaiting approval.</li><li><b>Analytics integration</b> has not been configured.</li><li><b>Final mobile QA</b> has not started.</li></ol><div className="suggestion"><small>SUGGESTED NEXT ACTION</small><strong>Schedule a 20-minute review with Maya and Daniel.</strong></div></div></div><div className="copilot-actions">{['Summarize','Find blockers','Create task','Draft update'].map((x,i)=><button key={x}><span>{['S','B','+','D'][i]}</span>{x}<ArrowRight size={13}/></button>)}<div className="ask-input"><span>Ask anything…</span><kbd>⌘ K</kbd></div></div></div></section>

   <section className="workflow section"><SectionLabel index="04">WORKFLOW</SectionLabel><div className="workflow-head"><h2>From signal<br/><span>to action.</span></h2><div className="workflow-track">{['Capture','Understand','Prioritize','Act','Learn'].map((x,i)=><motion.div key={x} whileHover={{y:-6}}><span>0{i+1}</span><strong>{x}</strong><p>{['Meetings, messages, docs and tasks.','ORBIT connects context.','AI identifies what matters.','Teams move the work forward.','Progress becomes organizational memory.'][i]}</p></motion.div>)}</div></div></section>

   <section className="control section"><SectionLabel index="05">PROJECT CONTROL CENTER</SectionLabel><div className="control-heading"><div><h2>A clearer view of<br/><span>the moving parts.</span></h2><p>One project surface for health, dependencies, owners and the next decision.</p></div><div className="project-tabs">{(['Overview','Timeline','Tasks','AI'] as Tab[]).map(t=><button key={t} className={projectTab===t?'active':''} onClick={()=>setProjectTab(t)}>{t}</button>)}</div></div><div className="control-app panel"><div className="control-top"><div><small>PROJECT / WEBSITE RELAUNCH</small><h3>72% <span>complete</span></h3></div><div className="health-pill"><i/> HEALTH / GOOD</div></div><AnimatePresence mode="wait"><motion.div key={projectTab} initial={{opacity:0,x:10}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-10}} className="control-content">{projectTab==='Overview'&&<><div className="metric-row"><div><small>TASKS</small><strong>12</strong><span>remaining</span></div><div><small>BLOCKERS</small><strong>3</strong><span>attention needed</span></div><div><small>NEXT MILESTONE</small><strong>Sep 28</strong><span>launch candidate</span></div></div><div className="control-lower"><div className="bars">{[34,48,43,67,58,82,72].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}<span>PROJECT VELOCITY</span></div><div className="reco"><Sparkles size={15}/><small>AI RECOMMENDATION</small><strong>Resolve analytics ownership before starting mobile QA.</strong><button>Review dependency <ArrowRight size={13}/></button></div></div></>}{projectTab==='Timeline'&&<div className="timeline-big">{['Discovery','Build','QA','Launch'].map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong><i style={{width:`${[100,82,54,24][i]}%`}}/><small>{['Complete','In progress','Starts Sep 20','Sep 28'][i]}</small></div>)}</div>}{projectTab==='Tasks'&&<div className="task-table">{['Finalize homepage','Analytics integration','Mobile QA','Launch checklist'].map((x,i)=><div key={x}><button><span>{i<1?<Check size={12}/>:''}</span>{x}</button><em>{['Maya','Daniel','Alex','Sofia'][i]}</em><small>{['Done','Blocked','Next','Queued'][i]}</small></div>)}</div>}{projectTab==='AI'&&<div className="ai-project"><Sparkles/><h3>Three decisions are gating the next milestone.</h3><p>ORBIT found a dependency chain across the homepage, analytics and QA tasks. Resolve ownership first; the rest can proceed without a meeting.</p><Button>Open decision queue</Button></div>}</motion.div></AnimatePresence></div></section>

   <section className="meeting section"><SectionLabel index="06">MEETING INTELLIGENCE</SectionLabel><div className="split-title"><h2>Meetings that keep working<br/><span>after the meeting ends.</span></h2><p>ORBIT converts conversation into durable organizational memory — without asking someone to become the note-taker.</p></div><div className="meeting-app panel"><div className="transcript"><div className="meeting-head"><div><small>PRODUCT STRATEGY — MONDAY 10:00</small><h3>Product Strategy</h3></div><span>4 participants</span></div>{['Maya · “We should commit to the beta date if onboarding is stable.”','Daniel · “Analytics is the only integration still at risk.”','Alex · “Mobile QA can start as soon as copy is approved.”','Sofia · “Let’s lock the review for Friday.”'].map((x,i)=><div className="quote" key={x}><b>{['10:04','10:11','10:18','10:24'][i]}</b><p>{x}</p></div>)}</div><div className="meeting-insight"><div className="switch"><button className={meeting==='transcript'?'active':''} onClick={()=>setMeeting('transcript')}>Transcript</button><button className={meeting==='actions'?'active':''} onClick={()=>setMeeting('actions')}>Extracted</button></div><AnimatePresence mode="wait">{meeting==='transcript'?<motion.div key="t" initial={{opacity:0}} animate={{opacity:1}} className="extract-preview"><Sparkles/><p>ORBIT is listening for decisions, actions and risks.</p></motion.div>:<motion.div key="a" initial={{opacity:0}} animate={{opacity:1}} className="extracted"><div><span>03</span><strong>Decisions</strong><p>Launch beta September 28</p></div><div><span>05</span><strong>Actions</strong><p>Daniel → finalize onboarding flow</p></div><div><span>02</span><strong>Risks</strong><p>Analytics implementation delayed</p></div></motion.div>}</AnimatePresence></div></div></section>

   <section className="knowledge section"><SectionLabel index="07">KNOWLEDGE</SectionLabel><div className="knowledge-grid"><div><h2>Your team&apos;s memory,<br/><span>finally connected.</span></h2><p>Search the why, not just the file name. ORBIT links documents, decisions, projects, meetings and people.</p></div><div className="search-app panel"><div className="searchbar"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Why did we change the pricing?"/><kbd>⌘ ↵</kbd></div>{result.length?result.map((x,i)=><button className="search-result" key={x}><FileText size={15}/><div><strong>{x}</strong><small>{['Decision · Pricing · 8 references','Meeting · Product · 14 references','Decision · Product · 5 references'][i]}</small></div><ChevronRight size={14}/></button>):<div className="empty">No local results. Try “pricing”.</div>}</div></div></section>

   <section className="automation section"><SectionLabel index="08">AUTOMATIONS</SectionLabel><div className="automation-head"><h2>Build systems<br/><span>that run themselves.</span></h2><p>Translate your team&apos;s operating rules into quiet, reliable workflows.</p></div><div className="automation-builder panel">{[['A project becomes blocked','Notify project owner','Create review task'],['A meeting ends','Summarize decisions','Create action items']].map((a,i)=><div className="automation-row" key={a[0]}><button className={'toggle '+(auto[i]?'on':'')} onClick={()=>setAuto(v=>v.map((x,j)=>j===i?!x:x))}><i/></button><div><small>WHEN</small><strong>{a[0]}</strong></div><ArrowRight/><div><small>THEN</small><strong>{a[1]}</strong></div><ArrowRight/><div><small>AND</small><strong>{a[2]}</strong></div><span className="enabled">{auto[i]?'ACTIVE':'PAUSED'}</span></div>)}<button className="add-rule"><span>+</span> Add automation rule</button></div></section>

   <section className="analytics section"><SectionLabel index="09">ANALYTICS</SectionLabel><div className="analytics-head"><h2>Progress you can<br/><span>actually act on.</span></h2><small>ILLUSTRATIVE PRODUCT DATA</small></div><div className="stats"><div><small>PROJECT VELOCITY</small><strong>+18%</strong><div className="sparkline"><i/><i/><i/><i/><i/><i/><i/></div></div><div><small>BLOCKERS</small><strong>-32%</strong><div className="sparkline down"><i/><i/><i/><i/><i/><i/><i/></div></div><div><small>ON-TIME DELIVERY</small><strong>94%</strong><div className="ring"><span>94</span></div></div><div><small>TEAM FOCUS</small><strong>87%</strong><div className="focusbar"><i/></div></div></div></section>

   <section className="integrations section"><SectionLabel index="10">INTEGRATIONS</SectionLabel><div className="integration-head"><h2>Connect the tools<br/><span>you already use.</span></h2><p>ORBIT sits across the tools your team trusts, adding context instead of another silo.</p></div><div className="integration-orbit"><OrbitCore/><div className="integration-names">{['Slack','Notion','Google Drive','GitHub','Linear','Figma','Google Calendar','Microsoft Teams'].map(x=><motion.div key={x} whileHover={{scale:1.04}}><span>{x.slice(0,2).toUpperCase()}</span>{x}</motion.div>)}</div></div></section>

   <section className="trust section"><div className="trust-copy"><SectionLabel index="11">TRUST</SectionLabel><h2>Built for the work you<br/><span>cannot afford to lose.</span></h2><p>Enterprise-ready architecture and careful controls for teams operating on important information.</p></div><div className="trust-grid">{[['Encryption','Data protected in transit and at rest.'],['Role-based access','Granular permissions by workspace and project.'],['Audit history','Audit-friendly activity history across work.'],['SSO','Centralized access for growing teams.'],['Permissions','Control who can discover and change context.'],['Data controls','Keep ownership clear as teams scale.']].map(([a,b])=><div key={a}><ShieldCheck size={17}/><strong>{a}</strong><p>{b}</p><small>FICTIONAL PRODUCT POSITIONING</small></div>)}</div></section>

   <section className="solutions section" id="solutions"><SectionLabel index="12">SOLUTIONS</SectionLabel><div className="solutions-layout"><div className="case-nav">{(Object.keys(useCases) as Array<keyof typeof useCases>).map(x=><button key={x} className={caseName===x?'active':''} onClick={()=>setCaseName(x)}><span>{useCases[x].icon}</span>{x}<ChevronRight size={15}/></button>)}</div><AnimatePresence mode="wait"><motion.div key={caseName} initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} className="case-panel"><div><small>ORBIT FOR {caseName.toUpperCase()}</small><h2>{useCases[caseName].copy}</h2><strong>{useCases[caseName].metric}</strong></div><div className="case-workflow">{useCases[caseName].workflow.map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><ArrowRight size={14}/></div>)}</div></motion.div></AnimatePresence></div></section>

   <section className="tour section"><SectionLabel index="13">PRODUCT TOUR</SectionLabel><div className="tour-head"><h2>One workspace.<br/><span>Every moving part.</span></h2><p>Move through the product lifecycle without losing the context that connects each stage.</p></div><div className="tour-tabs">{(['Plan','Build','Review','Launch'] as Tour[]).map((x,i)=><button key={x} className={tour===x?'active':''} onClick={()=>setTour(x)}><span>0{i+1}</span>{x}</button>)}</div><div className="tour-product panel"><div className="tour-sidebar"><small>WEBSITE RELAUNCH</small>{tourData[tour].map((x,i)=><div key={x}><span>{i+1}</span>{x}</div>)}</div><div className="tour-main"><div className="tour-meta"><span>PROJECT / {tour.toUpperCase()}</span><b>{tour==='Plan'?'42%':tour==='Build'?'68%':tour==='Review'?'84%':'96%'} ready</b></div><div className="tour-bars">{tourData[tour].map((x,i)=><div key={x}><small>{x}</small><i><b style={{width:`${70+i*8}%`}}/></i></div>)}</div><div className="tour-callout"><Sparkles size={15}/><span>ORBIT recommends</span><strong>{tour==='Plan'?'Align owners before work starts.':tour==='Build'?'Resolve the analytics dependency.':tour==='Review'?'Close the two remaining risks.':'Run final launch readiness review.'}</strong></div></div></div></section>

   <section className="pricing section" id="pricing"><SectionLabel index="14">PRICING</SectionLabel><div className="pricing-head"><div><h2>Simple enough<br/><span>to start today.</span></h2><small>ILLUSTRATIVE CONCEPT PRICING</small></div><div className="billing"><button className={!annual?'active':''} onClick={()=>setAnnual(false)}>Monthly</button><button className={annual?'active':''} onClick={()=>setAnnual(true)}>Annual <em>save 20%</em></button></div></div><div className="price-grid"><div className="price-card"><small>STARTER</small><strong>$0</strong><p>For small teams exploring ORBIT.</p><Button secondary>Start free</Button><span>Core workspace · 3 users · 2 projects</span></div><div className="price-card featured"><div className="popular">MOST POPULAR</div><small>TEAM</small><strong>$16 <i>/ user / month</i></strong><p>For growing teams. {annual?'Billed annually.':'Billed monthly.'}</p><Button>Start team</Button><span>Unlimited projects · AI context · Automations</span></div><div className="price-card"><small>SCALE</small><strong>Custom</strong><p>For larger organizations with advanced needs.</p><Button secondary>Talk to ORBIT</Button><span>SSO · Granular controls · Dedicated support</span></div></div></section>

   <section className="final-cta orbit-grid"><OrbitCore/><div><div className="eyebrow">THE NEXT MOVE</div><h2>Move the work<br/><em>forward.</em></h2><p>Bring your projects, people and knowledge into one intelligent workspace.</p><div className="hero-actions"><Button>Start Free</Button><Button secondary>Explore the Platform</Button></div></div></section>
  </main>
  <footer><div className="logo">ORBIT</div><span>AI-powered operating system for teams.</span><span>© 2026 ORBIT — fictional concept.</span></footer>
  <AnimatePresence>{cmd&&<motion.div className="command-overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setCmd(false)}><motion.div className="command-modal panel" initial={{y:20,scale:.98}} animate={{y:0,scale:1}} onClick={e=>e.stopPropagation()}><div className="command-search"><Command/><input autoFocus placeholder="Ask ORBIT to find, plan or act…"/><kbd>ESC</kbd></div><div className="command-list"><button><Search/> Find a project</button><button><Sparkles/> Summarize this workspace</button><button><Zap/> Show blockers</button><button><Check/> Create a task</button></div></motion.div></motion.div>}</AnimatePresence>
 </div>
}
