"use client";
import { useState } from "react";
import { ArrowRight, Check, Menu, X } from "lucide-react";
const programs=[['01','Strength','Build raw strength with structured progressive training.'],['02','Conditioning','Engineered sessions to improve endurance, speed and recovery.'],['03','Performance','Sport-focused programming for people who refuse average.']];
const stats=[['12','Weeks'],['4','Training phases'],['24/7','Member access']];
export default function VoltPage(){const[open,setOpen]=useState(false);return <main className="volt-site bg-[#090909] text-[#f5f5f5]">
<header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-black/70 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8"><a href="#top" className="font-black italic tracking-[-.08em] text-2xl">VOLT<span className="text-[#c7ff2f]">.</span></a><nav className="hidden gap-8 text-[11px] font-semibold uppercase tracking-[.18em] text-white/55 md:flex"><a href="#programs">Programs</a><a href="#method">Method</a><a href="#studio">Studio</a></nav><a href="#join" className="hidden rounded-full bg-[#c7ff2f] px-5 py-2.5 text-[10px] font-bold uppercase tracking-[.18em] text-black sm:inline-flex">Start training</a><button onClick={()=>setOpen(true)} className="md:hidden" aria-label="Open menu"><Menu/></button></div></header>
{open&&<div className="fixed inset-0 z-[60] bg-[#090909] p-6"><button className="float-right" onClick={()=>setOpen(false)} aria-label="Close menu"><X/></button><nav className="mt-24 grid gap-7 text-5xl font-black italic"><a href="#programs" onClick={()=>setOpen(false)}>Programs</a><a href="#method" onClick={()=>setOpen(false)}>Method</a><a href="#studio" onClick={()=>setOpen(false)}>Studio</a><a href="#join" onClick={()=>setOpen(false)}>Join</a></nav></div>}
<section id="top" className="relative flex min-h-[92svh] items-end overflow-hidden"><div className="absolute inset-0 volt-hero-image"/><div className="absolute inset-0 bg-gradient-to-t from-black via-black/35 to-black/20"/><div className="relative mx-auto w-full max-w-7xl px-5 pb-14 sm:px-8 sm:pb-20"><p className="text-[10px] font-bold uppercase tracking-[.3em] text-[#c7ff2f]">Performance training · Delhi</p><h1 className="mt-5 max-w-5xl text-[5.5rem] font-black italic leading-[.78] tracking-[-.08em] sm:text-[10rem] md:text-[13rem]">TRAIN<br/><span className="text-[#c7ff2f]">HARDER.</span></h1><div className="mt-9 flex flex-col justify-between gap-6 border-t border-white/20 pt-6 sm:flex-row sm:items-end"><p className="max-w-md text-sm leading-7 text-white/60">A performance studio for people who train with intent. Strength, conditioning and coaching without the fluff.</p><a href="#join" className="inline-flex w-fit items-center gap-3 rounded-full bg-[#c7ff2f] px-6 py-3.5 text-[10px] font-bold uppercase tracking-[.18em] text-black">Start training <ArrowRight size={15}/></a></div></div></section>
<section id="method" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 sm:py-32"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><p className="text-[10px] font-bold uppercase tracking-[.3em] text-white/35">01 / The method</p><div><h2 className="max-w-4xl text-5xl font-black italic leading-[.9] tracking-[-.05em] sm:text-7xl">NO RANDOM WORKOUTS.<br/><span className="text-white/35">JUST PROGRESS.</span></h2><p className="mt-8 max-w-2xl text-base leading-8 text-white/50">Every session has a purpose. We build training around your baseline, track the work and progress the stimulus as you adapt.</p><div className="mt-12 grid gap-3 sm:grid-cols-3">{stats.map(([n,l])=><div key={l} className="border border-white/10 p-5"><p className="text-3xl font-black italic text-[#c7ff2f]">{n}</p><p className="mt-2 text-xs uppercase tracking-[.18em] text-white/40">{l}</p></div>)}</div></div></div></section>
<section id="programs" className="border-y border-white/10 bg-[#101010]"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8 sm:py-32"><p className="text-[10px] font-bold uppercase tracking-[.3em] text-[#c7ff2f]">02 / Programs</p><div className="mt-8 divide-y divide-white/10 border-y border-white/10">{programs.map(([n,title,desc])=><div key={title} className="group grid gap-5 py-8 sm:grid-cols-[80px_1fr_auto] sm:items-center"><span className="text-xs text-white/25">{n}</span><div><h3 className="text-3xl font-black italic tracking-[-.04em] transition group-hover:text-[#c7ff2f]">{title}</h3><p className="mt-2 max-w-xl text-sm text-white/45">{desc}</p></div><ArrowRight className="text-white/30 transition group-hover:translate-x-1 group-hover:text-[#c7ff2f]"/></div>)}</div></div></section>
<section id="studio" className="mx-auto grid max-w-7xl gap-8 px-5 py-24 sm:px-8 sm:py-32 lg:grid-cols-[1.2fr_.8fr] lg:items-center"><div className="volt-studio-image min-h-[520px]"/><div><p className="text-[10px] font-bold uppercase tracking-[.3em] text-[#c7ff2f]">03 / The studio</p><h2 className="mt-5 text-6xl font-black italic leading-[.82] tracking-[-.06em] sm:text-8xl">BUILT<br/><span className="text-white/30">FOR WORK.</span></h2><div className="mt-8 space-y-4 text-sm text-white/50">{['Small-group coaching','Premium strength floor','Recovery-focused environment'].map(x=><p key={x} className="flex gap-3"><Check size={16} className="text-[#c7ff2f]"/>{x}</p>)}</div></div></section>
<section id="join" className="border-t border-white/10 px-5 py-28 text-center sm:px-8 sm:py-40"><p className="text-[10px] font-bold uppercase tracking-[.3em] text-[#c7ff2f]">04 / Start now</p><h2 className="mx-auto mt-5 max-w-4xl text-6xl font-black italic leading-[.8] tracking-[-.07em] sm:text-9xl">YOUR NEXT<br/><span className="text-[#c7ff2f]">LEVEL.</span></h2><p className="mx-auto mt-8 max-w-md text-sm leading-7 text-white/45">Book a trial session and see what focused training feels like.</p><a href="mailto:hello@volt.example" className="mt-9 inline-flex rounded-full bg-[#c7ff2f] px-8 py-4 text-[10px] font-bold uppercase tracking-[.2em] text-black">Book a trial</a></section>
<footer className="border-t border-white/10 px-5 py-9 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 sm:flex-row"><div><div className="text-xl font-black italic">VOLT<span className="text-[#c7ff2f]">.</span></div><p className="mt-1 text-[10px] uppercase tracking-[.18em] text-white/25">Performance studio · Delhi</p></div><p className="text-[10px] uppercase tracking-[.18em] text-white/25">© 2026 VOLT · Concept Project</p></div></footer></main>}
